lamp.nacos.ip=${NACOS_IP:@nacos.ip@}
lamp.nacos.port=${NACOS_PORT:@nacos.port@}
lamp.nacos.namespace=${NACOS_NAMESPACE:@nacos.namespace@}
lamp.nacos.username=${NACOS_USERNAME:@nacos.username@}
lamp.nacos.password=${NACOS_PASSWORD:@nacos.password@}

mybatis.print-sql=true

# mysql config
mysql.host=127.0.0.1:3306
mysql.db=lamp_ds_c_defaults
mysql.username=root
mysql.password=root
