lamp.nacos.ip=${NACOS_IP:@nacos.ip@}
lamp.nacos.port=${NACOS_PORT:@nacos.port@}
lamp.nacos.namespace=${NACOS_NAMESPACE:@nacos.namespace@}
lamp.nacos.username=${NACOS_USERNAME:@nacos.username@}
lamp.nacos.password=${NACOS_PASSWORD:@nacos.password@}

mybatis.print-sql=true

# manager cache type, local/redis
gateway.manager.cache-type=redis

# mysql config
mysql.host=127.0.0.1:3306
mysql.db=lamp_ds_c_defaults
mysql.username=root
mysql.password=root

# redis config
spring.data.redis.host=localhost
spring.data.redis.port=16379
spring.data.redis.database=6
spring.data.redis.password='SbtyMveYNfLzTks7H0apCmyStPzWJqjy'
