# \u9ED8\u8BA4\u6FC0\u6D3B\u73AF\u5883
spring.profiles.active=dev
# \u9879\u76EE\u540D\u79F0
spring.application.name=@project.artifactId@
# \u9879\u76EE\u7AEF\u53E3\u53F7
server.port=18750

####### gateway config #######
# \u63A5\u53E3\u8BF7\u6C42\u5165\u53E3\u524D\u7F00
gateway.path=/api
# restfull\u98CE\u683C\u63A5\u53E3\u8BF7\u6C42\u5165\u53E3\u524D\u7F00
gateway.rest=/rest
# \u7F13\u5B58\u7C7B\u578B local/redis \u4E8C\u9009\u4E00\uFF0C \u9ED8\u8BA4\u672C\u5730\u662F\u5185\u5B58\uFF0C\u5176\u4ED6\u73AF\u5883\u662Fredis
gateway.manager.cache-type=local
# api \u7F13\u5B58\u7C7B\u578B,local/redis
gateway.manager.api=${gateway.manager.cache-type}
# isv \u7F13\u5B58\u7C7B\u578B,local/redis
gateway.manager.isv=${gateway.manager.cache-type}
# \u79D8\u94A5\u7F13\u5B58\u7C7B\u578B,local/redis
gateway.manager.secret=${gateway.manager.cache-type}
# \u63A5\u53E3\u6743\u9650\u7F13\u5B58\u7C7B\u578B,local/redis
gateway.manager.isv-api-perm=${gateway.manager.cache-type}
# \u7F51\u5173\u8FD4\u56DE\u7ED3\u679Cjson\u5E8F\u5217\u5316\u5DE5\u5177: fastjson2/gson
gateway.serialize.json-formatter=fastjson2
# \u5E8F\u5217\u5316\u65E5\u671F\u683C\u5F0F
gateway.serialize.date-format=yyyy-MM-dd HH:mm:ss

####### \u53C2\u6570\u540D\u79F0\u5B9A\u4E49 #######
api.app-id-name=app_id
api.api-name=method
api.format-name=format
api.charset-name=charset
api.sign-type-name=sign_type
api.sign-name=sign
api.timestamp-name=timestamp
api.version-name=version
api.notify-url-name=notify_url
api.app-auth-token-name=app_auth_token
api.biz-content-name=biz_content

####### \u5176\u4ED6\u914D\u7F6E #######
# \u63A5\u53E3\u8BF7\u6C42\u6709\u6548\u65F6\u95F4
api.timeout-seconds=300
# \u65F6\u95F4\u6233\u683C\u5F0F\u5316
api.timestamp-pattern=yyyy-MM-dd HH:mm:ss
# \u9ED8\u8BA4\u65F6\u533A
api.zone-id=Asia/Shanghai


####### dubbo \u914D\u7F6E #######
dubbo.protocol.name=dubbo
dubbo.protocol.port=-1
dubbo.protocol.parameters.sba=ignore
dubbo.application.qos-enable=false
# ### register config see:https://cn.dubbo.apache.org/zh-cn/overview/mannual/java-sdk/reference-manual/registry/overview/
# ------
# nacos://localhost:8848        Cluster config:nacos://localhost:8848?backup=localshot:8846,localshot:8847
# zookeeper://localhost:2181    Cluster config:zookeeper://10.20.153.10:2181?backup=10.20.153.11:2181,10.20.153.12:2181
# redis://localhost:6379        Cluster config:redis://10.20.153.10:6379?backup=10.20.153.11:6379,10.20.153.12:6379
# ------
dubbo.registry.address=nacos://${lamp.nacos.username}:${lamp.nacos.password}@${lamp.nacos.ip}:${lamp.nacos.port}?namespace=${lamp.nacos.namespace}

# \u8BF7\u6C42\u4F53\u6700\u5927\u503C, 10MB
# 1KB = 1024
# 1MB = 1048576
# 1GB = 1073741824
# 1TB = 1099511627776
dubbo.protocol.payload=10485760

####### file upload config #######
# \u5355\u4E2A\u6587\u4EF6\u5185\u5BB9\u5927\u5C0F\u6700\u5927\u9650\u5236
upload.one-file-max-size=10MB
# \u603B\u6587\u4EF6\u5185\u5BB9\u5927\u5C0F\u6700\u5927\u9650\u5236
upload.total-file-max-size=50MB
# \u786E\u4FDD\u8FD9\u4E2A\u914D\u7F6E\u6BD4 {upload.one-file-max-size} \u5927
spring.servlet.multipart.max-file-size=60MB
# \u786E\u4FDD\u8FD9\u4E2A\u914D\u7F6E\u6BD4 {upload.total-file-max-size} and {dubbo.protocol.payload} \u5927
spring.servlet.multipart.max-request-size=200MB

####### \u6570\u636E\u5E93\u914D\u7F6E #######
mysql.host=127.0.0.1:3306
mysql.db=lamp_ds_c_defaults
mysql.username=root
mysql.password=root

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.url=jdbc:mysql://${mysql.host}/${mysql.db}?useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&serverTimezone=Asia/Shanghai
spring.datasource.username=${mysql.username}
spring.datasource.password=${mysql.password}

####### \u7F13\u5B58\u914D\u7F6E #######
spring.data.redis.host=localhost
spring.data.redis.port=16379
spring.data.redis.database=6
spring.data.redis.password=SbtyMveYNfLzTks7H0apCmyStPzWJqjy

####### mybatis\u914D\u7F6E #######
mybatis.fill.com.gitee.fastmybatis.core.support.LocalDateTimeFillInsert=created_time
mybatis.fill.com.gitee.fastmybatis.core.support.LocalDateTimeFillUpdate=updated_time
# mybatis config file
mybatis.config-location=classpath:mybatis/mybatisConfig.xml
# print sql, true/false
mybatis.print-sql=false

# log level
logging.level.com.gitee.sop=info
# log path
logging.file.name=logs/${spring.application.name}/root.log
# print SQL
logging.level.com.gitee.sop.gateway.dao=error
logging.level.com.gitee.fastmybatis=info

