CREATE TABLE "BASE_DICT"
(
"ID" BIGINT NOT NULL,
"PARENT_ID" BIGINT NOT NULL,
"PARENT_KEY" VARCHAR(255 CHAR) DEFAULT '',
"KEY_" VARCHAR(255 CHAR) DEFAULT '' NOT NULL,
"CLASSIFY" CHAR(2 CHAR) DEFAULT '20' NOT NULL,
"NAME" VARCHAR(255 CHAR) DEFAULT '' NOT NULL,
"STATE" BIT DEFAULT 1,
"REMARK" VARCHAR(255 CHAR) DEFAULT '',
"SORT_VALUE" INT DEFAULT 1,
"ICON" VARCHAR(255 CHAR) DEFAULT '',
"CSS_STYLE" VARCHAR(255 CHAR) DEFAULT '',
"CSS_CLASS" VARCHAR(255 CHAR) DEFAULT '',
"CREATED_BY" BIGINT,
"CREATED_TIME" TIMESTAMP(0),
"UPDATED_BY" BIGINT,
"UPDATED_TIME" TIMESTAMP(0),
"CREATED_ORG_ID" BIGINT,
NOT CLUSTER PRIMARY KEY("ID")) STORAGE(ON "MAIN", CLUSTERBTR) ;

COMMENT ON TABLE BASE_DICT IS '字典';
COMMENT ON COLUMN BASE_DICT."CLASSIFY" IS '分类;[10-系统字典 20-业务字典]@Echo(api = EchoApi.DICTIONARY_ITEM_FEIGN_CLASS, dictType = EchoDictType.System.DICT_CLASSIFY)';
COMMENT ON COLUMN BASE_DICT."CREATED_BY" IS '创建人';
COMMENT ON COLUMN BASE_DICT."CREATED_ORG_ID" IS '创建人组织';
COMMENT ON COLUMN BASE_DICT."CREATED_TIME" IS '创建时间';
COMMENT ON COLUMN BASE_DICT."CSS_CLASS" IS 'css类元素';
COMMENT ON COLUMN BASE_DICT."CSS_STYLE" IS 'css样式';
COMMENT ON COLUMN BASE_DICT."ICON" IS '图标';
COMMENT ON COLUMN BASE_DICT."ID" IS 'ID';
COMMENT ON COLUMN BASE_DICT."KEY_" IS '标识';
COMMENT ON COLUMN BASE_DICT."NAME" IS '名称';
COMMENT ON COLUMN BASE_DICT."PARENT_ID" IS '所属字典';
COMMENT ON COLUMN BASE_DICT."PARENT_KEY" IS '所属字典标识';
COMMENT ON COLUMN BASE_DICT."REMARK" IS '备注';
COMMENT ON COLUMN BASE_DICT."SORT_VALUE" IS '排序';
COMMENT ON COLUMN BASE_DICT."STATE" IS '状态';
COMMENT ON COLUMN BASE_DICT."UPDATED_BY" IS '更新人';
COMMENT ON COLUMN BASE_DICT."UPDATED_TIME" IS '更新时间';


CREATE TABLE "BASE_EMPLOYEE"
(
"ID" BIGINT NOT NULL,
"IS_DEFAULT" BIT DEFAULT 0 NOT NULL,
"POSITION_ID" BIGINT,
"USER_ID" BIGINT NOT NULL,
"LAST_COMPANY_ID" BIGINT,
"LAST_DEPT_ID" BIGINT,
"REAL_NAME" VARCHAR(255 CHAR) DEFAULT '' NOT NULL,
"ACTIVE_STATUS" CHAR(2 CHAR) DEFAULT '20',
"POSITION_STATUS" CHAR(2 CHAR) DEFAULT '10',
"STATE" BIT DEFAULT 1,
"CREATED_BY" BIGINT,
"CREATED_TIME" TIMESTAMP(0),
"UPDATED_BY" BIGINT,
"UPDATED_TIME" TIMESTAMP(0),
"CREATED_ORG_ID" BIGINT,
NOT CLUSTER PRIMARY KEY("ID"),
CONSTRAINT "UK_EMP_USER_ID" UNIQUE("USER_ID")) STORAGE(ON "MAIN", CLUSTERBTR) ;

COMMENT ON TABLE BASE_EMPLOYEE IS '员工';
COMMENT ON COLUMN BASE_EMPLOYEE."ACTIVE_STATUS" IS '激活状态;[10-未激活 20-已激活]@Echo(api = EchoApi.DICTIONARY_ITEM_FEIGN_CLASS, dictType = EchoDictType.Global.ACTIVE_STATUS)';
COMMENT ON COLUMN BASE_EMPLOYEE."CREATED_BY" IS '创建人';
COMMENT ON COLUMN BASE_EMPLOYEE."CREATED_ORG_ID" IS '创建人组织';
COMMENT ON COLUMN BASE_EMPLOYEE."CREATED_TIME" IS '创建时间';
COMMENT ON COLUMN BASE_EMPLOYEE."ID" IS 'ID';
COMMENT ON COLUMN BASE_EMPLOYEE."IS_DEFAULT" IS '是否默认员工;[0-否 1-是]';
COMMENT ON COLUMN BASE_EMPLOYEE."LAST_COMPANY_ID" IS '上一次登录单位ID';
COMMENT ON COLUMN BASE_EMPLOYEE."LAST_DEPT_ID" IS '上一次登录部门ID';
COMMENT ON COLUMN BASE_EMPLOYEE."POSITION_ID" IS '所属岗位';
COMMENT ON COLUMN BASE_EMPLOYEE."POSITION_STATUS" IS '职位状态;[10-在职 20-离职]@Echo(api = EchoApi.DICTIONARY_ITEM_FEIGN_CLASS, dictType = EchoDictType.Base.POSITION_STATUS)';
COMMENT ON COLUMN BASE_EMPLOYEE."REAL_NAME" IS '真实姓名';
COMMENT ON COLUMN BASE_EMPLOYEE."STATE" IS '状态;[0-禁用 1-启用]';
COMMENT ON COLUMN BASE_EMPLOYEE."UPDATED_BY" IS '最后更新人';
COMMENT ON COLUMN BASE_EMPLOYEE."UPDATED_TIME" IS '最后更新时间';
COMMENT ON COLUMN BASE_EMPLOYEE."USER_ID" IS '用户';


CREATE TABLE "BASE_EMPLOYEE_ORG_REL"
(
"ID" BIGINT NOT NULL,
"ORG_ID" BIGINT NOT NULL,
"EMPLOYEE_ID" BIGINT NOT NULL,
"CREATED_BY" BIGINT,
"CREATED_TIME" TIMESTAMP(0),
"UPDATED_BY" BIGINT,
"UPDATED_TIME" TIMESTAMP(0),
"CREATED_ORG_ID" BIGINT,
NOT CLUSTER PRIMARY KEY("ID"),
CONSTRAINT "UK_EMPLOYEE_ORG" UNIQUE("ORG_ID", "EMPLOYEE_ID")) STORAGE(ON "MAIN", CLUSTERBTR) ;

COMMENT ON TABLE BASE_EMPLOYEE_ORG_REL IS '员工所在部门';
COMMENT ON COLUMN BASE_EMPLOYEE_ORG_REL."CREATED_BY" IS '创建人';
COMMENT ON COLUMN BASE_EMPLOYEE_ORG_REL."CREATED_ORG_ID" IS '创建人组织';
COMMENT ON COLUMN BASE_EMPLOYEE_ORG_REL."CREATED_TIME" IS '创建时间';
COMMENT ON COLUMN BASE_EMPLOYEE_ORG_REL."EMPLOYEE_ID" IS '关联员工';
COMMENT ON COLUMN BASE_EMPLOYEE_ORG_REL."ID" IS 'ID';
COMMENT ON COLUMN BASE_EMPLOYEE_ORG_REL."ORG_ID" IS '关联机构';
COMMENT ON COLUMN BASE_EMPLOYEE_ORG_REL."UPDATED_BY" IS '最后更新人';
COMMENT ON COLUMN BASE_EMPLOYEE_ORG_REL."UPDATED_TIME" IS '最后更新时间';


CREATE TABLE "BASE_EMPLOYEE_ROLE_REL"
(
"ID" BIGINT NOT NULL,
"ROLE_ID" BIGINT NOT NULL,
"EMPLOYEE_ID" BIGINT NOT NULL,
"CREATED_BY" BIGINT,
"CREATED_TIME" TIMESTAMP(0),
"UPDATED_BY" BIGINT,
"UPDATED_TIME" TIMESTAMP(0),
"CREATED_ORG_ID" BIGINT,
NOT CLUSTER PRIMARY KEY("ID"),
CONSTRAINT "UK_ERR_ROLE_EMPLOYEE" UNIQUE("ROLE_ID", "EMPLOYEE_ID")) STORAGE(ON "MAIN", CLUSTERBTR) ;

COMMENT ON TABLE BASE_EMPLOYEE_ROLE_REL IS '员工的角色';
COMMENT ON COLUMN BASE_EMPLOYEE_ROLE_REL."CREATED_BY" IS '创建人';
COMMENT ON COLUMN BASE_EMPLOYEE_ROLE_REL."CREATED_ORG_ID" IS '创建人组织';
COMMENT ON COLUMN BASE_EMPLOYEE_ROLE_REL."CREATED_TIME" IS '创建时间';
COMMENT ON COLUMN BASE_EMPLOYEE_ROLE_REL."EMPLOYEE_ID" IS '所属员工;#base_employee';
COMMENT ON COLUMN BASE_EMPLOYEE_ROLE_REL."ID" IS 'ID';
COMMENT ON COLUMN BASE_EMPLOYEE_ROLE_REL."ROLE_ID" IS '拥有角色;#base_role';
COMMENT ON COLUMN BASE_EMPLOYEE_ROLE_REL."UPDATED_BY" IS '最后更新人';
COMMENT ON COLUMN BASE_EMPLOYEE_ROLE_REL."UPDATED_TIME" IS '最后更新时间';


CREATE TABLE "BASE_OPERATION_LOG"
(
"ID" BIGINT NOT NULL,
"REQUEST_IP" VARCHAR(50 CHAR) DEFAULT '',
"TYPE" VARCHAR(5 CHAR) DEFAULT 'OPT',
"USER_NAME" VARCHAR(50 CHAR) DEFAULT '',
"DESCRIPTION" VARCHAR(255 CHAR) DEFAULT '',
"CLASS_PATH" VARCHAR(255 CHAR) DEFAULT '',
"ACTION_METHOD" VARCHAR(50 CHAR) DEFAULT '',
"REQUEST_URI" VARCHAR(500 CHAR) DEFAULT '',
"HTTP_METHOD" VARCHAR(10 CHAR) DEFAULT 'GET',
"START_TIME" TIMESTAMP(0),
"FINISH_TIME" TIMESTAMP(0),
"CONSUMING_TIME" BIGINT DEFAULT 0,
"UA" VARCHAR(500 CHAR) DEFAULT '',
"CREATED_TIME" TIMESTAMP(0),
"CREATED_BY" BIGINT,
"UPDATED_TIME" TIMESTAMP(0),
"UPDATED_BY" BIGINT,
"CREATED_ORG_ID" BIGINT,
NOT CLUSTER PRIMARY KEY("ID")) STORAGE(ON "MAIN", CLUSTERBTR) ;

COMMENT ON TABLE BASE_OPERATION_LOG IS '操作日志';
COMMENT ON COLUMN BASE_OPERATION_LOG."ACTION_METHOD" IS '请求方法';
COMMENT ON COLUMN BASE_OPERATION_LOG."CLASS_PATH" IS '类路径';
COMMENT ON COLUMN BASE_OPERATION_LOG."CONSUMING_TIME" IS '消耗时间';
COMMENT ON COLUMN BASE_OPERATION_LOG."CREATED_BY" IS '创建人';
COMMENT ON COLUMN BASE_OPERATION_LOG."CREATED_ORG_ID" IS '创建人组织';
COMMENT ON COLUMN BASE_OPERATION_LOG."CREATED_TIME" IS '创建时间';
COMMENT ON COLUMN BASE_OPERATION_LOG."DESCRIPTION" IS '操作描述';
COMMENT ON COLUMN BASE_OPERATION_LOG."FINISH_TIME" IS '完成时间';
COMMENT ON COLUMN BASE_OPERATION_LOG."HTTP_METHOD" IS '请求类型;#HttpMethod{GET:GET请求;POST:POST请求;PUT:PUT请求;DELETE:DELETE请求;PATCH:PATCH请求;TRACE:TRACE请求;HEAD:HEAD请求;OPTIONS:OPTIONS请求;}';
COMMENT ON COLUMN BASE_OPERATION_LOG."ID" IS '主键';
COMMENT ON COLUMN BASE_OPERATION_LOG."REQUEST_IP" IS '操作IP';
COMMENT ON COLUMN BASE_OPERATION_LOG."REQUEST_URI" IS '请求地址';
COMMENT ON COLUMN BASE_OPERATION_LOG."START_TIME" IS '开始时间';
COMMENT ON COLUMN BASE_OPERATION_LOG."TYPE" IS '日志类型;#LogType{OPT:操作类型;EX:异常类型}';
COMMENT ON COLUMN BASE_OPERATION_LOG."UA" IS '浏览器';
COMMENT ON COLUMN BASE_OPERATION_LOG."UPDATED_BY" IS '最后更新人';
COMMENT ON COLUMN BASE_OPERATION_LOG."UPDATED_TIME" IS '最后更新时间';
COMMENT ON COLUMN BASE_OPERATION_LOG."USER_NAME" IS '操作人';


CREATE TABLE "BASE_OPERATION_LOG_EXT"
(
"ID" BIGINT NOT NULL,
"PARAMS" CLOB,
"RESULT" CLOB,
"EX_DETAIL" CLOB,
"CREATED_TIME" TIMESTAMP(0),
"CREATED_BY" BIGINT,
"UPDATED_TIME" TIMESTAMP(0),
"UPDATED_BY" BIGINT,
"CREATED_ORG_ID" BIGINT,
NOT CLUSTER PRIMARY KEY("ID")) STORAGE(ON "MAIN", CLUSTERBTR) ;

COMMENT ON TABLE BASE_OPERATION_LOG_EXT IS '操作日志扩展';
COMMENT ON COLUMN BASE_OPERATION_LOG_EXT."CREATED_BY" IS '创建人';
COMMENT ON COLUMN BASE_OPERATION_LOG_EXT."CREATED_ORG_ID" IS '创建人组织';
COMMENT ON COLUMN BASE_OPERATION_LOG_EXT."CREATED_TIME" IS '创建时间';
COMMENT ON COLUMN BASE_OPERATION_LOG_EXT."EX_DETAIL" IS '异常描述';
COMMENT ON COLUMN BASE_OPERATION_LOG_EXT."ID" IS '主键';
COMMENT ON COLUMN BASE_OPERATION_LOG_EXT."PARAMS" IS '请求参数';
COMMENT ON COLUMN BASE_OPERATION_LOG_EXT."RESULT" IS '返回值';
COMMENT ON COLUMN BASE_OPERATION_LOG_EXT."UPDATED_BY" IS '最后更新人ID';
COMMENT ON COLUMN BASE_OPERATION_LOG_EXT."UPDATED_TIME" IS '最后更新时间';


CREATE TABLE "BASE_ORG"
(
"ID" BIGINT NOT NULL,
"NAME" VARCHAR(255 CHAR) NOT NULL,
"TYPE_" CHAR(2 CHAR) DEFAULT '10',
"SHORT_NAME" VARCHAR(255 CHAR),
"PARENT_ID" BIGINT,
"TREE_GRADE" INT DEFAULT 0,
"TREE_PATH" VARCHAR(255 CHAR),
"SORT_VALUE" INT DEFAULT 1,
"STATE" BIT DEFAULT 1,
"REMARKS" VARCHAR(255 CHAR),
"CREATED_TIME" TIMESTAMP(0),
"CREATED_BY" BIGINT,
"UPDATED_TIME" TIMESTAMP(0),
"UPDATED_BY" BIGINT,
"CREATED_ORG_ID" BIGINT,
NOT CLUSTER PRIMARY KEY("ID"),
CONSTRAINT "UK_ORG_NAME" UNIQUE("NAME")) STORAGE(ON "MAIN", CLUSTERBTR) ;

COMMENT ON TABLE BASE_ORG IS '组织';
COMMENT ON COLUMN BASE_ORG."CREATED_BY" IS '创建人';
COMMENT ON COLUMN BASE_ORG."CREATED_ORG_ID" IS '创建人组织';
COMMENT ON COLUMN BASE_ORG."CREATED_TIME" IS '创建时间';
COMMENT ON COLUMN BASE_ORG."ID" IS 'ID';
COMMENT ON COLUMN BASE_ORG."NAME" IS '名称';
COMMENT ON COLUMN BASE_ORG."PARENT_ID" IS '父组织';
COMMENT ON COLUMN BASE_ORG."REMARKS" IS '备注';
COMMENT ON COLUMN BASE_ORG."SHORT_NAME" IS '简称';
COMMENT ON COLUMN BASE_ORG."SORT_VALUE" IS '排序';
COMMENT ON COLUMN BASE_ORG."STATE" IS '状态;[0-禁用 1-启用]';
COMMENT ON COLUMN BASE_ORG."TREE_GRADE" IS '树层级';
COMMENT ON COLUMN BASE_ORG."TREE_PATH" IS '树路径;用id拼接树结构';
COMMENT ON COLUMN BASE_ORG."TYPE_" IS '类型;[10-单位 20-部门]@Echo(api = EchoApi.DICTIONARY_ITEM_FEIGN_CLASS, dictType = EchoDictType.Base.ORG_TYPE)';
COMMENT ON COLUMN BASE_ORG."UPDATED_BY" IS '修改人';
COMMENT ON COLUMN BASE_ORG."UPDATED_TIME" IS '修改时间';


CREATE TABLE "BASE_ORG_ROLE_REL"
(
"ID" BIGINT NOT NULL,
"ORG_ID" BIGINT NOT NULL,
"ROLE_ID" BIGINT NOT NULL,
"CREATED_TIME" TIMESTAMP(0),
"CREATED_BY" BIGINT,
"UPDATED_TIME" TIMESTAMP(0),
"UPDATED_BY" BIGINT,
"CREATED_ORG_ID" BIGINT,
NOT CLUSTER PRIMARY KEY("ID"),
CONSTRAINT "UK_ORG_ROLE" UNIQUE("ORG_ID", "ROLE_ID")) STORAGE(ON "MAIN", CLUSTERBTR) ;

COMMENT ON TABLE BASE_ORG_ROLE_REL IS '组织的角色';
COMMENT ON COLUMN BASE_ORG_ROLE_REL."CREATED_BY" IS '创建人';
COMMENT ON COLUMN BASE_ORG_ROLE_REL."CREATED_ORG_ID" IS '创建人组织';
COMMENT ON COLUMN BASE_ORG_ROLE_REL."CREATED_TIME" IS '创建时间';
COMMENT ON COLUMN BASE_ORG_ROLE_REL."ID" IS 'ID';
COMMENT ON COLUMN BASE_ORG_ROLE_REL."ORG_ID" IS '所属部门;#base_org';
COMMENT ON COLUMN BASE_ORG_ROLE_REL."ROLE_ID" IS '拥有角色;#base_role';
COMMENT ON COLUMN BASE_ORG_ROLE_REL."UPDATED_BY" IS '最后更新人';
COMMENT ON COLUMN BASE_ORG_ROLE_REL."UPDATED_TIME" IS '最后更新时间';


CREATE TABLE "BASE_PARAMETER"
(
"ID" BIGINT NOT NULL,
"KEY_" VARCHAR(255 CHAR) DEFAULT '' NOT NULL,
"VALUE" VARCHAR(255 CHAR) DEFAULT '' NOT NULL,
"NAME" VARCHAR(255 CHAR) DEFAULT '' NOT NULL,
"REMARKS" VARCHAR(255 CHAR) DEFAULT '',
"STATE" BIT DEFAULT 1,
"PARAM_TYPE" CHAR(2 CHAR) DEFAULT '20',
"CREATED_BY" BIGINT,
"CREATED_TIME" TIMESTAMP(0),
"UPDATED_BY" BIGINT,
"UPDATED_TIME" TIMESTAMP(0),
"CREATED_ORG_ID" BIGINT,
NOT CLUSTER PRIMARY KEY("ID")) STORAGE(ON "MAIN", CLUSTERBTR) ;

COMMENT ON TABLE BASE_PARAMETER IS '个性参数';
COMMENT ON COLUMN BASE_PARAMETER."CREATED_BY" IS '创建人id';
COMMENT ON COLUMN BASE_PARAMETER."CREATED_ORG_ID" IS '创建人组织';
COMMENT ON COLUMN BASE_PARAMETER."CREATED_TIME" IS '创建时间';
COMMENT ON COLUMN BASE_PARAMETER."ID" IS 'ID';
COMMENT ON COLUMN BASE_PARAMETER."KEY_" IS '参数键';
COMMENT ON COLUMN BASE_PARAMETER."NAME" IS '参数名称';
COMMENT ON COLUMN BASE_PARAMETER."PARAM_TYPE" IS '类型;[10-系统参数 20-业务参数]@Echo(api = EchoApi.DICTIONARY_ITEM_FEIGN_CLASS, dictType = EchoDictType.System.PARAMETER_TYPE)';
COMMENT ON COLUMN BASE_PARAMETER."REMARKS" IS '备注';
COMMENT ON COLUMN BASE_PARAMETER."STATE" IS '状态';
COMMENT ON COLUMN BASE_PARAMETER."UPDATED_BY" IS '更新人id';
COMMENT ON COLUMN BASE_PARAMETER."UPDATED_TIME" IS '更新时间';
COMMENT ON COLUMN BASE_PARAMETER."VALUE" IS '参数值';


CREATE TABLE "BASE_POSITION"
(
"ID" BIGINT NOT NULL,
"NAME" VARCHAR(255 CHAR) DEFAULT '' NOT NULL,
"ORG_ID" BIGINT,
"STATE" BIT DEFAULT 1,
"REMARKS" VARCHAR(255 CHAR) DEFAULT '',
"CREATED_TIME" TIMESTAMP(0),
"CREATED_BY" BIGINT,
"UPDATED_TIME" TIMESTAMP(0),
"UPDATED_BY" BIGINT,
"CREATED_ORG_ID" BIGINT,
NOT CLUSTER PRIMARY KEY("ID"),
CONSTRAINT "UK_NAME" UNIQUE("NAME")) STORAGE(ON "MAIN", CLUSTERBTR) ;

COMMENT ON TABLE BASE_POSITION IS '岗位';
COMMENT ON COLUMN BASE_POSITION."CREATED_BY" IS '创建人';
COMMENT ON COLUMN BASE_POSITION."CREATED_ORG_ID" IS '创建人组织';
COMMENT ON COLUMN BASE_POSITION."CREATED_TIME" IS '创建时间';
COMMENT ON COLUMN BASE_POSITION."ID" IS 'ID';
COMMENT ON COLUMN BASE_POSITION."NAME" IS '名称';
COMMENT ON COLUMN BASE_POSITION."ORG_ID" IS '所属组织;#base_org@Echo(api = EchoApi.ORG_ID_CLASS)';
COMMENT ON COLUMN BASE_POSITION."REMARKS" IS '备注';
COMMENT ON COLUMN BASE_POSITION."STATE" IS '状态;0-禁用 1-启用';
COMMENT ON COLUMN BASE_POSITION."UPDATED_BY" IS '修改人';
COMMENT ON COLUMN BASE_POSITION."UPDATED_TIME" IS '修改时间';


CREATE TABLE "BASE_ROLE"
(
"ID" BIGINT NOT NULL,
"CATEGORY" CHAR(2 CHAR) DEFAULT '10' NOT NULL,
"TYPE_" CHAR(2 CHAR) DEFAULT '20' NOT NULL,
"NAME" VARCHAR(50 CHAR) NOT NULL,
"CODE" VARCHAR(20 CHAR) NOT NULL,
"REMARKS" VARCHAR(255 CHAR),
"STATE" BIT DEFAULT 1,
"READONLY_" BIT DEFAULT 0,
"CREATED_BY" BIGINT,
"CREATED_TIME" TIMESTAMP(0),
"UPDATED_BY" BIGINT,
"UPDATED_TIME" TIMESTAMP(0),
"CREATED_ORG_ID" BIGINT,
NOT CLUSTER PRIMARY KEY("ID"),
CONSTRAINT "UK_CODE" UNIQUE("CODE")) STORAGE(ON "MAIN", CLUSTERBTR) ;

COMMENT ON TABLE BASE_ROLE IS '角色';
COMMENT ON COLUMN BASE_ROLE."CATEGORY" IS '角色类别;[10-功能角色 20-桌面角色 30-数据角色]@Echo(api = EchoApi.DICTIONARY_ITEM_FEIGN_CLASS, dictType = EchoDictType.Base.ROLE_CATEGORY)';
COMMENT ON COLUMN BASE_ROLE."CODE" IS '编码';
COMMENT ON COLUMN BASE_ROLE."CREATED_BY" IS '创建人';
COMMENT ON COLUMN BASE_ROLE."CREATED_ORG_ID" IS '创建人组织';
COMMENT ON COLUMN BASE_ROLE."CREATED_TIME" IS '创建时间';
COMMENT ON COLUMN BASE_ROLE."ID" IS 'ID';
COMMENT ON COLUMN BASE_ROLE."NAME" IS '名称';
COMMENT ON COLUMN BASE_ROLE."READONLY_" IS '内置角色';
COMMENT ON COLUMN BASE_ROLE."REMARKS" IS '备注';
COMMENT ON COLUMN BASE_ROLE."STATE" IS '状态';
COMMENT ON COLUMN BASE_ROLE."TYPE_" IS '角色类型;[10-系统角色 20-自定义角色]; 
@Echo(api = EchoApi.DICTIONARY_ITEM_FEIGN_CLASS, dictType = EchoDictType.Global.DATA_TYPE)';
COMMENT ON COLUMN BASE_ROLE."UPDATED_BY" IS '更新人';
COMMENT ON COLUMN BASE_ROLE."UPDATED_TIME" IS '更新时间';


CREATE TABLE "BASE_ROLE_RESOURCE_REL"
(
"ID" BIGINT NOT NULL,
"RESOURCE_ID" BIGINT NOT NULL,
"APPLICATION_ID" BIGINT NOT NULL,
"ROLE_ID" BIGINT NOT NULL,
"CREATED_TIME" TIMESTAMP(0),
"CREATED_BY" BIGINT,
"UPDATED_TIME" TIMESTAMP(0),
"UPDATED_BY" BIGINT,
"CREATED_ORG_ID" BIGINT,
NOT CLUSTER PRIMARY KEY("ID"),
CONSTRAINT "UK_ROLE_RESOURCE" UNIQUE("RESOURCE_ID", "ROLE_ID")) STORAGE(ON "MAIN", CLUSTERBTR) ;

COMMENT ON TABLE BASE_ROLE_RESOURCE_REL IS '角色的资源';
COMMENT ON COLUMN BASE_ROLE_RESOURCE_REL."APPLICATION_ID" IS '所属应用;#def_application';
COMMENT ON COLUMN BASE_ROLE_RESOURCE_REL."CREATED_BY" IS '创建人';
COMMENT ON COLUMN BASE_ROLE_RESOURCE_REL."CREATED_ORG_ID" IS '创建人组织';
COMMENT ON COLUMN BASE_ROLE_RESOURCE_REL."CREATED_TIME" IS '创建时间';
COMMENT ON COLUMN BASE_ROLE_RESOURCE_REL."ID" IS '主键';
COMMENT ON COLUMN BASE_ROLE_RESOURCE_REL."RESOURCE_ID" IS '拥有资源;#def_resource';
COMMENT ON COLUMN BASE_ROLE_RESOURCE_REL."ROLE_ID" IS '所属角色;#base_role';
COMMENT ON COLUMN BASE_ROLE_RESOURCE_REL."UPDATED_BY" IS '最后更新人';
COMMENT ON COLUMN BASE_ROLE_RESOURCE_REL."UPDATED_TIME" IS '最后更新时间';


CREATE TABLE "EXTEND_INTERFACE_LOG"
(
"ID" BIGINT NOT NULL,
"INTERFACE_ID" BIGINT NOT NULL,
"NAME" VARCHAR(255 CHAR) NOT NULL,
"SUCCESS_COUNT" INT DEFAULT 0,
"FAIL_COUNT" INT DEFAULT 0,
"LAST_EXEC_TIME" TIMESTAMP(0),
"CREATED_TIME" TIMESTAMP(0),
"CREATED_BY" BIGINT,
"UPDATED_TIME" TIMESTAMP(0),
"UPDATED_BY" BIGINT,
NOT CLUSTER PRIMARY KEY("ID"),
CONSTRAINT "UK_EIL_INTERFACE_ID" UNIQUE("INTERFACE_ID")) STORAGE(ON "MAIN", CLUSTERBTR) ;

COMMENT ON TABLE EXTEND_INTERFACE_LOG IS '接口执行日志';
COMMENT ON COLUMN EXTEND_INTERFACE_LOG."CREATED_BY" IS '创建人';
COMMENT ON COLUMN EXTEND_INTERFACE_LOG."CREATED_TIME" IS '创建时间';
COMMENT ON COLUMN EXTEND_INTERFACE_LOG."FAIL_COUNT" IS '失败次数';
COMMENT ON COLUMN EXTEND_INTERFACE_LOG."INTERFACE_ID" IS '接口ID;
#extend_interface';
COMMENT ON COLUMN EXTEND_INTERFACE_LOG."LAST_EXEC_TIME" IS '最后执行时间';
COMMENT ON COLUMN EXTEND_INTERFACE_LOG."NAME" IS '接口名称';
COMMENT ON COLUMN EXTEND_INTERFACE_LOG."SUCCESS_COUNT" IS '成功次数';
COMMENT ON COLUMN EXTEND_INTERFACE_LOG."UPDATED_BY" IS '修改人';
COMMENT ON COLUMN EXTEND_INTERFACE_LOG."UPDATED_TIME" IS '修改时间';


CREATE TABLE "EXTEND_INTERFACE_LOGGING"
(
"ID" BIGINT NOT NULL,
"LOG_ID" BIGINT NOT NULL,
"EXEC_TIME" TIMESTAMP(0) NOT NULL,
"STATUS" CHAR(2 CHAR) DEFAULT '01',
"PARAMS" CLOB,
"RESULT" CLOB,
"ERROR_MSG" CLOB,
"BIZ_ID" BIGINT,
"CREATED_TIME" TIMESTAMP(0),
"CREATED_BY" BIGINT,
"UPDATED_TIME" TIMESTAMP(0),
"UPDATED_BY" BIGINT,
NOT CLUSTER PRIMARY KEY("ID")) STORAGE(ON "MAIN", CLUSTERBTR) ;

COMMENT ON TABLE EXTEND_INTERFACE_LOGGING IS '接口执行日志记录';
COMMENT ON COLUMN EXTEND_INTERFACE_LOGGING."BIZ_ID" IS '业务ID';
COMMENT ON COLUMN EXTEND_INTERFACE_LOGGING."CREATED_BY" IS '创建人';
COMMENT ON COLUMN EXTEND_INTERFACE_LOGGING."CREATED_TIME" IS '创建时间';
COMMENT ON COLUMN EXTEND_INTERFACE_LOGGING."ERROR_MSG" IS '异常信息';
COMMENT ON COLUMN EXTEND_INTERFACE_LOGGING."EXEC_TIME" IS '执行时间';
COMMENT ON COLUMN EXTEND_INTERFACE_LOGGING."LOG_ID" IS '接口日志ID;
#extend_interface_log';
COMMENT ON COLUMN EXTEND_INTERFACE_LOGGING."PARAMS" IS '请求参数';
COMMENT ON COLUMN EXTEND_INTERFACE_LOGGING."RESULT" IS '接口返回';
COMMENT ON COLUMN EXTEND_INTERFACE_LOGGING."STATUS" IS '执行状态;[01-初始化 02-成功 03-失败]@Echo(api = EchoApi.DICTIONARY_ITEM_FEIGN_CLASS, dictType = EchoDictType.Base.MSG_INTERFACE_LOGGING_STATUS)';
COMMENT ON COLUMN EXTEND_INTERFACE_LOGGING."UPDATED_BY" IS '修改人';
COMMENT ON COLUMN EXTEND_INTERFACE_LOGGING."UPDATED_TIME" IS '修改时间';


CREATE TABLE "EXTEND_MSG"
(
"ID" BIGINT NOT NULL,
"TEMPLATE_CODE" VARCHAR(255 CHAR),
"TYPE" CHAR(2 CHAR),
"STATUS" VARCHAR(10 CHAR),
"CHANNEL" VARCHAR(255 CHAR),
"PARAM" TEXT,
"TITLE" VARCHAR(255 CHAR),
"CONTENT" CLOB,
"SEND_TIME" TIMESTAMP(0),
"BIZ_ID" BIGINT,
"BIZ_TYPE" VARCHAR(255 CHAR),
"REMIND_MODE" CHAR(2 CHAR),
"AUTHOR" VARCHAR(255 CHAR),
"CREATED_BY" BIGINT,
"CREATED_TIME" TIMESTAMP(0),
"UPDATED_BY" BIGINT,
"UPDATED_TIME" TIMESTAMP(0),
"CREATED_ORG_ID" BIGINT,
NOT CLUSTER PRIMARY KEY("ID")) STORAGE(ON "MAIN", CLUSTERBTR) ;

COMMENT ON TABLE EXTEND_MSG IS '消息';
COMMENT ON COLUMN EXTEND_MSG."AUTHOR" IS '发布人姓名';
COMMENT ON COLUMN EXTEND_MSG."BIZ_ID" IS '业务ID';
COMMENT ON COLUMN EXTEND_MSG."BIZ_TYPE" IS '业务类型';
COMMENT ON COLUMN EXTEND_MSG."CHANNEL" IS '发送渠道;
#SourceType{APP:应用;SERVICE:服务}';
COMMENT ON COLUMN EXTEND_MSG."CONTENT" IS '发送内容';
COMMENT ON COLUMN EXTEND_MSG."CREATED_BY" IS '创建人ID';
COMMENT ON COLUMN EXTEND_MSG."CREATED_ORG_ID" IS '创建人所属机构';
COMMENT ON COLUMN EXTEND_MSG."CREATED_TIME" IS '创建时间';
COMMENT ON COLUMN EXTEND_MSG."ID" IS '短信记录ID';
COMMENT ON COLUMN EXTEND_MSG."PARAM" IS '参数;需要封装为[{‘key’:‘‘,;’value’:‘‘}, {’key2’:‘‘, ’value2’:‘‘}]格式';
COMMENT ON COLUMN EXTEND_MSG."REMIND_MODE" IS '提醒方式;@Echo(api = EchoApi.DICTIONARY_ITEM_FEIGN_CLASS, dictType = EchoDictType.Base.NOTICE_REMIND_MODE)[01-待办 02-预警 03-提醒]';
COMMENT ON COLUMN EXTEND_MSG."SEND_TIME" IS '发送时间';
COMMENT ON COLUMN EXTEND_MSG."STATUS" IS '执行状态;
#TaskStatus{DRAFT:草稿;WAITING:等待执行;SUCCESS:执行成功;FAIL:执行失败}';
COMMENT ON COLUMN EXTEND_MSG."TEMPLATE_CODE" IS '消息模板;
#extend_msg_template';
COMMENT ON COLUMN EXTEND_MSG."TITLE" IS '标题';
COMMENT ON COLUMN EXTEND_MSG."TYPE" IS '消息类型;[01-短信 02-邮件 03-站内信];@Echo(api = EchoApi.DICTIONARY_ITEM_FEIGN_CLASS, dictType = EchoDictType.Base.MSG_TEMPLATE_TYPE)';
COMMENT ON COLUMN EXTEND_MSG."UPDATED_BY" IS '最后修改人';
COMMENT ON COLUMN EXTEND_MSG."UPDATED_TIME" IS '最后修改时间';


CREATE OR REPLACE  INDEX "TEMPATE_ID_TOPIC_CONTENT" ON "EXTEND_MSG"("TEMPLATE_CODE" ASC,"TITLE" ASC) STORAGE(ON "MAIN", CLUSTERBTR) ;

CREATE TABLE "EXTEND_MSG_RECIPIENT"
(
"ID" BIGINT NOT NULL,
"MSG_ID" BIGINT NOT NULL,
"RECIPIENT" VARCHAR(255 CHAR) NOT NULL,
"EXT" VARCHAR(255 CHAR),
"CREATED_BY" BIGINT,
"CREATED_TIME" TIMESTAMP(0),
"UPDATED_BY" BIGINT,
"UPDATED_TIME" TIMESTAMP(0),
NOT CLUSTER PRIMARY KEY("ID")) STORAGE(ON "MAIN", CLUSTERBTR) ;

COMMENT ON TABLE EXTEND_MSG_RECIPIENT IS '消息接收人';
COMMENT ON COLUMN EXTEND_MSG_RECIPIENT."CREATED_BY" IS '创建人';
COMMENT ON COLUMN EXTEND_MSG_RECIPIENT."CREATED_TIME" IS '创建时间';
COMMENT ON COLUMN EXTEND_MSG_RECIPIENT."EXT" IS '扩展信息';
COMMENT ON COLUMN EXTEND_MSG_RECIPIENT."ID" IS 'ID';
COMMENT ON COLUMN EXTEND_MSG_RECIPIENT."MSG_ID" IS '任务ID;
#extend_msg';
COMMENT ON COLUMN EXTEND_MSG_RECIPIENT."RECIPIENT" IS '接收人;
可能是手机号、邮箱、用户ID等';
COMMENT ON COLUMN EXTEND_MSG_RECIPIENT."UPDATED_BY" IS '最后修改人';
COMMENT ON COLUMN EXTEND_MSG_RECIPIENT."UPDATED_TIME" IS '最后修改时间';


CREATE OR REPLACE  INDEX "TASK_ID_TEL_NUM" ON "EXTEND_MSG_RECIPIENT"("MSG_ID" ASC,"RECIPIENT" ASC) STORAGE(ON "MAIN", CLUSTERBTR) ;

CREATE TABLE "EXTEND_MSG_TEMPLATE"
(
"ID" BIGINT NOT NULL,
"INTERFACE_ID" BIGINT NOT NULL,
"TYPE" CHAR(2 CHAR) NOT NULL,
"CODE" VARCHAR(255 CHAR) NOT NULL,
"NAME" VARCHAR(255 CHAR),
"STATE" BIT,
"TEMPLATE_CODE" VARCHAR(255 CHAR),
"SIGN" VARCHAR(255 CHAR),
"TITLE" VARCHAR(255 CHAR),
"CONTENT" CLOB NOT NULL,
"SCRIPT" VARCHAR(255 CHAR),
"PARAM" VARCHAR(255 CHAR),
"REMARKS" VARCHAR(255 CHAR),
"TARGET_" CHAR(2 CHAR),
"AUTO_READ" BIT DEFAULT 1,
"REMIND_MODE" CHAR(2 CHAR),
"URL" VARCHAR(255 CHAR),
"CREATED_BY" BIGINT,
"CREATED_TIME" TIMESTAMP(0),
"UPDATED_BY" BIGINT,
"UPDATED_TIME" TIMESTAMP(0),
NOT CLUSTER PRIMARY KEY("ID"),
CONSTRAINT "UK_EX_MSG_TEMPLATE_CODE" UNIQUE("CODE")) STORAGE(ON "MAIN", CLUSTERBTR) ;

COMMENT ON TABLE EXTEND_MSG_TEMPLATE IS '消息模板';
COMMENT ON COLUMN EXTEND_MSG_TEMPLATE."AUTO_READ" IS '自动已读';
COMMENT ON COLUMN EXTEND_MSG_TEMPLATE."CODE" IS '模板标识';
COMMENT ON COLUMN EXTEND_MSG_TEMPLATE."CONTENT" IS '模板内容';
COMMENT ON COLUMN EXTEND_MSG_TEMPLATE."CREATED_BY" IS '创建人ID';
COMMENT ON COLUMN EXTEND_MSG_TEMPLATE."CREATED_TIME" IS '创建时间';
COMMENT ON COLUMN EXTEND_MSG_TEMPLATE."ID" IS '模板ID';
COMMENT ON COLUMN EXTEND_MSG_TEMPLATE."INTERFACE_ID" IS '接口ID';
COMMENT ON COLUMN EXTEND_MSG_TEMPLATE."NAME" IS '模板名称';
COMMENT ON COLUMN EXTEND_MSG_TEMPLATE."PARAM" IS '模板参数';
COMMENT ON COLUMN EXTEND_MSG_TEMPLATE."REMARKS" IS '备注';
COMMENT ON COLUMN EXTEND_MSG_TEMPLATE."REMIND_MODE" IS '提醒方式;@Echo(api = EchoApi.DICTIONARY_ITEM_FEIGN_CLASS, dictType = EchoDictType.Base.NOTICE_REMIND_MODE)[01-待办 02-预警 03-提醒]';
COMMENT ON COLUMN EXTEND_MSG_TEMPLATE."SCRIPT" IS '脚本';
COMMENT ON COLUMN EXTEND_MSG_TEMPLATE."SIGN" IS '签名';
COMMENT ON COLUMN EXTEND_MSG_TEMPLATE."STATE" IS '状态';
COMMENT ON COLUMN EXTEND_MSG_TEMPLATE."TARGET_" IS '打开方式;@Echo(api = EchoApi.DICTIONARY_ITEM_FEIGN_CLASS, dictType = EchoDictType.Base.NOTICE_TARGET)[01-页面 02-弹窗 03-新开窗口]';
COMMENT ON COLUMN EXTEND_MSG_TEMPLATE."TEMPLATE_CODE" IS '模板编码';
COMMENT ON COLUMN EXTEND_MSG_TEMPLATE."TITLE" IS '标题';
COMMENT ON COLUMN EXTEND_MSG_TEMPLATE."TYPE" IS '消息类型;[01-短信 02-邮件 03-站内信];@Echo(api = EchoApi.DICTIONARY_ITEM_FEIGN_CLASS, dictType = EchoDictType.Base.MSG_TEMPLATE_TYPE)';
COMMENT ON COLUMN EXTEND_MSG_TEMPLATE."UPDATED_BY" IS '最后修改人';
COMMENT ON COLUMN EXTEND_MSG_TEMPLATE."UPDATED_TIME" IS '最后修改时间';
COMMENT ON COLUMN EXTEND_MSG_TEMPLATE."URL" IS '跳转地址';


CREATE TABLE "EXTEND_NOTICE"
(
"ID" BIGINT NOT NULL,
"MSG_ID" BIGINT,
"BIZ_ID" VARCHAR(64 CHAR),
"BIZ_TYPE" VARCHAR(64 CHAR),
"RECIPIENT_ID" BIGINT NOT NULL,
"REMIND_MODE" CHAR(2 CHAR) NOT NULL,
"TITLE" VARCHAR(255 CHAR),
"CONTENT" CLOB,
"AUTHOR" VARCHAR(255 CHAR),
"URL" VARCHAR(255 CHAR),
"TARGET_" CHAR(2 CHAR),
"AUTO_READ" BIT,
"HANDLE_TIME" TIMESTAMP(0),
"READ_TIME" TIMESTAMP(0),
"IS_READ" BIT DEFAULT 0,
"IS_HANDLE" BIT DEFAULT 0,
"CREATED_TIME" TIMESTAMP(0),
"CREATED_BY" BIGINT,
"UPDATED_TIME" TIMESTAMP(0),
"UPDATED_BY" BIGINT,
"CREATED_ORG_ID" BIGINT,
NOT CLUSTER PRIMARY KEY("ID")) STORAGE(ON "MAIN", CLUSTERBTR) ;

COMMENT ON TABLE EXTEND_NOTICE IS '通知表';
COMMENT ON COLUMN EXTEND_NOTICE."AUTHOR" IS '发布人';
COMMENT ON COLUMN EXTEND_NOTICE."AUTO_READ" IS '自动已读';
COMMENT ON COLUMN EXTEND_NOTICE."BIZ_ID" IS '业务ID';
COMMENT ON COLUMN EXTEND_NOTICE."BIZ_TYPE" IS '业务类型';
COMMENT ON COLUMN EXTEND_NOTICE."CONTENT" IS '内容';
COMMENT ON COLUMN EXTEND_NOTICE."CREATED_BY" IS '创建人id';
COMMENT ON COLUMN EXTEND_NOTICE."CREATED_ORG_ID" IS '所属组织';
COMMENT ON COLUMN EXTEND_NOTICE."CREATED_TIME" IS '创建时间';
COMMENT ON COLUMN EXTEND_NOTICE."HANDLE_TIME" IS '处理时间';
COMMENT ON COLUMN EXTEND_NOTICE."ID" IS 'ID';
COMMENT ON COLUMN EXTEND_NOTICE."IS_HANDLE" IS '是否处理';
COMMENT ON COLUMN EXTEND_NOTICE."IS_READ" IS '是否已读';
COMMENT ON COLUMN EXTEND_NOTICE."MSG_ID" IS '消息ID';
COMMENT ON COLUMN EXTEND_NOTICE."READ_TIME" IS '读取时间';
COMMENT ON COLUMN EXTEND_NOTICE."RECIPIENT_ID" IS '接收人';
COMMENT ON COLUMN EXTEND_NOTICE."REMIND_MODE" IS '提醒方式;@Echo(api = EchoApi.DICTIONARY_ITEM_FEIGN_CLASS, dictType = EchoDictType.Base.NOTICE_REMIND_MODE)[01-待办 02-预警 03-提醒]';
COMMENT ON COLUMN EXTEND_NOTICE."TARGET_" IS '打开方式;@Echo(api = EchoApi.DICTIONARY_ITEM_FEIGN_CLASS, dictType = EchoDictType.Base.NOTICE_TARGET)[01-页面 02-弹窗 03-新开窗口]';
COMMENT ON COLUMN EXTEND_NOTICE."TITLE" IS '标题';
COMMENT ON COLUMN EXTEND_NOTICE."UPDATED_BY" IS '最后修改人';
COMMENT ON COLUMN EXTEND_NOTICE."UPDATED_TIME" IS '最后修改时间';
COMMENT ON COLUMN EXTEND_NOTICE."URL" IS '处理地址';


CREATE TABLE "UNDO_LOG"
(
"ID" BIGINT AUTO_INCREMENT NOT NULL,
"BRANCH_ID" BIGINT NOT NULL,
"XID" VARCHAR(100 CHAR) NOT NULL,
"CONTEXT" VARCHAR(128 CHAR) NOT NULL,
"ROLLBACK_INFO" BLOB NOT NULL,
"LOG_STATUS" INT NOT NULL,
"LOG_CREATED" TIMESTAMP(6) NOT NULL,
"LOG_MODIFIED" TIMESTAMP(6) NOT NULL,
NOT CLUSTER PRIMARY KEY("ID"),
CONSTRAINT "UX_UNDO_LOG" UNIQUE("XID", "BRANCH_ID")) STORAGE(ON "MAIN", CLUSTERBTR) AUTO_INCREMENT = 1;

COMMENT ON TABLE UNDO_LOG IS 'AT transaction mode undo table';
COMMENT ON COLUMN UNDO_LOG."BRANCH_ID" IS 'branch transaction id';
COMMENT ON COLUMN UNDO_LOG."CONTEXT" IS 'undo_log context,such as serialization';
COMMENT ON COLUMN UNDO_LOG."ID" IS 'increment id';
COMMENT ON COLUMN UNDO_LOG."LOG_CREATED" IS 'create datetime';
COMMENT ON COLUMN UNDO_LOG."LOG_MODIFIED" IS 'modify datetime';
COMMENT ON COLUMN UNDO_LOG."LOG_STATUS" IS '0:normal status,1:defense status';
COMMENT ON COLUMN UNDO_LOG."ROLLBACK_INFO" IS 'rollback info';
COMMENT ON COLUMN UNDO_LOG."XID" IS 'global transaction id';


